### ISSUE TITLE
Regarding to type of output MFs 

### ISSUE THREAD

**Issue by QianShi17** [Haghrah/PyIT2FLS#1]
Hi Haghrah,

Many thanks for your great work on providing this IT2 toolbox in Python environment. It is very well developed and easy to use. I was considering using this toolbox in my research work. 

But I just came across an issue when I used this toolbox. In my research environment, I would like the type of FIS to be Sugeno type instead of Mamdani type, which means I am expecting the type of output MFs to be Singleton (Type1) or constant values (numerical functions). According to the examples you provided, I found that it seems that the output MFs are all type2 ones. I just would like to ask if I can still use this toolbox when the output MFs are type1 or constants. 

Many thanks for your attention and hope I can get reply from you soon.

**Comment by Haghrah** [comment]
Hi QianShi17,

It will not be very soon but in the next version, TSK model support would be added.

Best regards.
