### ISSUE TITLE
pyPSO

### ISSUE THREAD

**Issue by eugenpar** [Haghrah/PyIT2FLS#3]
Hi!
Program it2fls_ex4.py uses the pyPSO module, but there is no source link in the project documentation.
The following sources are found on the Internet:
 https://github.com/marcelcaraciolo/pypso	
 https://pypi.org/project/pyPSO/
 https://github.com/oh2gxn/pypso
But it doesn't look like these are the necessary ones. Where are the ends?
Evgeniy

**Comment by Haghrah** [comment]
It is included in the examples folder: [https://github.com/Haghrah/PyIT2FLS/blob/master/examples/PyPSO.py](https://github.com/Haghrah/PyIT2FLS/blob/master/examples/PyPSO.py)
Check the example, and let me know if there is any problem.

Best regards.

**Comment by eugenpar** [comment]
Program ex4.py it works well, thank you for your prompt response.
I will begin to get acquainted with the program in more depth. There will be new questions.
Evgeniy
