### ISSUE TITLE
Predication

### ISSUE THREAD

**Issue by eugenpar** [Haghrah/PyIT2FLS#4]
Hi! Example 4 involves predicting a time series. Whether the forecast period can be set. how, for example, is it done in FB prophet?Evgeniy

**Comment by Haghrah** [comment]
Hello,

In the fourth example, the time series under study is considered to be of auto-regressive type. So the inputs of the predictor system are some consecutive values of the time series. This example can be updated in such a way that it works as FB Prophet. But it is not an easy task. First, you must consider a model (auto-regressive, or further as a direct function of external parameters) based on the properties of your time series. Then based on the model chosen, the inputs of the fuzzy predictor system will be determined. Now, you can prepare the learning data with the desired period and determine the parameters of the fuzzy system.

Best regards,
Amir Arslan Haghrah

**Comment by eugenpar** [comment]
This is all great, but I'm interested in whether you have any ready-made developments in this case. I can't raise this problem myself.And the combination of "fuzzy logic + bee swarm" seems to be the most promising method in terms of time series forecasting. Each of these methods separately does not achieve the goal.Evgeniy.

**Comment by Haghrah** [comment]
No, I have not such a code.
