### ISSUE TITLE
CoA defuzzification method error

### ISSUE THREAD

**Issue by guiaugustoga987** [Haghrah/PyIT2FLS#5]
Hello,

I'm trying to use the CoA defuzzification method with the minimum engine just like the code line below : 

`SYS = T1Mamdani(engine="Minimum", defuzzification="CoA")`

But I keep getting the message : 

nan

/usr/local/lib/python3.7/dist-packages/pyit2fls/pyit2fls.py:723: RuntimeWarning: invalid value encountered in double_scalars
  return int1 / int2

If I use the "CoG" method with the same inputs everything works as intended. Am I doing something wrong ?

Here is the code I'm testing :

```
domain1 = np.arange(-1.8, 1.8, 0.001)
domain2 = np.arange(-2, 2, 0.001)
domain3 = np.arange(-1, 1, 0.001)

ze = 0.001406210978590027
dot_ze = 0.00234235235

vsp = [-0.000,0.001,0.04,0.07,1]
sp = [0.05,0.10,0.24,0.29,1]
mp = [0.24,0.34,0.48,0.58,1]
bp = [0.48,0.58,1.8,1.81,1]

VSP = T1FS(domain1,trapezoid_mf, [vsp[0],vsp[1],vsp[2],vsp[3],vsp[4]])
SP = T1FS(domain1,trapezoid_mf, [sp[0],sp[1],sp[2],sp[3],sp[4]])
MP = T1FS(domain1,trapezoid_mf, [mp[0],mp[1],mp[2],mp[3],mp[4]])
BP = T1FS(domain1,trapezoid_mf, [bp[0],bp[1],bp[2],bp[3],bp[4]])

VSN = T1FS(domain1,trapezoid_mf, [-vsp[3],-vsp[2],-vsp[1],-vsp[0],vsp[4]])
SN = T1FS(domain1,trapezoid_mf, [-sp[3],-sp[2],-sp[1],-sp[0],sp[4]])
MN = T1FS(domain1,trapezoid_mf, [-mp[3],-mp[2],-mp[1],-mp[0],mp[4]])
BN = T1FS(domain1,trapezoid_mf, [-bp[3],-bp[2],-bp[1],-bp[0],bp[4]])

#T1FS_plot(VSP,SP,MP,BP,VSN,SN,MN,BN)

der = 2

N = T1FS(domain2,trapezoid_mf, [-2.1,-2,-der,0,1])
P = T1FS(domain2,trapezoid_mf, [0,der,2,2.1,1])
Z = T1FS(domain2,tri_mf, [-der,0,der,1])
#T1FS_plot(N,P,Z)

fat = 1
fat1 = 1

mpp = [-0.0001,0.00,0.001,0.05,1]
pp = [0.0,fat*0.05,fat*0.1,fat*0.15,1]
mep = [fat*0.1,fat*0.18,fat*0.22,fat*0.3,1]
gp = [fat*0.22,fat*0.3,1,1.01,1]

MPP = T1FS(domain3,trapezoid_mf, [mpp[0],mpp[1],mpp[2],mpp[3],mpp[4]])
PP = T1FS(domain3,trapezoid_mf, [pp[0],pp[1],pp[2],pp[3],pp[4]])
MEP = T1FS(domain3,trapezoid_mf, [mep[0],mep[1],mep[2],mep[3],mep[4]])
GP = T1FS(domain3,trapezoid_mf, [gp[0],gp[1],gp[2],gp[3],gp[4]])

MPN = T1FS(domain3,trapezoid_mf, [-mpp[3],-mpp[2],-mpp[1],-mpp[0],mpp[4]])
PN = T1FS(domain3,trapezoid_mf, [-pp[3],-pp[2],-pp[1],-pp[0],pp[4]])
MEN = T1FS(domain3,trapezoid_mf, [-mep[3],-mep[2],-mep[1],-mep[0],mep[4]])
GN = T1FS(domain3,trapezoid_mf, [-gp[3],-gp[2],-gp[1],-gp[0],gp[4]])

T1FS_plot(MPP,PP,MEP,GP,MPN,PN,MEN,GN)

#SYS = T1Mamdani(engine="Minimum", defuzzification="CoG")
SYS = T1Mamdani(engine="Minimum", defuzzification="CoA")

SYS.add_input_variable("ze")  # E
SYS.add_input_variable("dot_ze")  # dot E
SYS.add_output_variable("vy")
#######################################################
SYS.add_rule([("ze", BP), ("dot_ze", N)], [("vy",MEN)])
SYS.add_rule([("ze", MP), ("dot_ze", N)], [("vy",PN)])
SYS.add_rule([("ze", SP), ("dot_ze", N)], [("vy",MPN)])
SYS.add_rule([("ze", VSP), ("dot_ze", N)], [("vy",MPN)])

SYS.add_rule([("ze", BN), ("dot_ze", N)], [("vy",MEP)])
SYS.add_rule([("ze", MN), ("dot_ze", N)], [("vy",PP)])
SYS.add_rule([("ze", SN), ("dot_ze", N)], [("vy",MPP)])
SYS.add_rule([("ze", VSN), ("dot_ze", N)], [("vy",MPP)])
########################################################
SYS.add_rule([("ze", BP), ("dot_ze", Z)], [("vy",GN)])
SYS.add_rule([("ze", MP), ("dot_ze", Z)], [("vy",MEN)])
SYS.add_rule([("ze", SP), ("dot_ze", Z)], [("vy",PN)])
SYS.add_rule([("ze", VSP), ("dot_ze", Z)], [("vy",MPN)])

SYS.add_rule([("ze", BN), ("dot_ze", Z)], [("vy",GP)])
SYS.add_rule([("ze", MN), ("dot_ze", Z)], [("vy",MEP)])
SYS.add_rule([("ze", SN), ("dot_ze", Z)], [("vy",PP)])
SYS.add_rule([("ze", VSN), ("dot_ze", Z)], [("vy",MPP)])
########################################################
SYS.add_rule([("ze", BP), ("dot_ze", P)], [("vy",GN)])
SYS.add_rule([("ze", MP), ("dot_ze", P)], [("vy",GN)])
SYS.add_rule([("ze", SP), ("dot_ze", P)], [("vy",MEN)])
SYS.add_rule([("ze", VSP), ("dot_ze", P)], [("vy",PN)])

SYS.add_rule([("ze", BN), ("dot_ze", P)], [("vy",GP)])
SYS.add_rule([("ze", MN), ("dot_ze", P)], [("vy",GP)])
SYS.add_rule([("ze", SN), ("dot_ze", P)], [("vy",MEP)])
SYS.add_rule([("ze", VSN), ("dot_ze", P)], [("vy",PP)])
########################################################



#t,s = SYS.evaluate({"ze":ze, "dot_ze":dot_ze})
s = SYS.evaluate({"ze":ze, "dot_ze":dot_ze})

vy = s["vy"]
print(vy)
```

Thank you for your work !

**Comment by Haghrah** [comment]
Hi!
Thanks a lot for writing to me!

This is the theoretical problem of the CoG defuzzification method. When you evaluate the Fuzzy rules, if a rule ends up with a Fuzzy set with zero membership value all over its domain, the denominator of the equation used to calculate the CoG would be zero. So if you try to calculate the CoG on a paper, you will also get division by zero. This problem originates from the fact that the trapezoid or triangular sets have zero membership value in some parts of their domain. Theoretically, this means that if you use Gaussian Fuzzy sets, you will not get trapped in such a situation. For example, using a triangular set "-1 is POSITIVE" yields an absolute zero, and then using a t-norm makes the resulting Fuzzy set an all zero Fuzzy set. But when you use Gaussian sets, it will be a small value like 0.0001, which prevents division by zero.

If you are forced to use triangular or trapezoidal sets along with the CoG method, as far as I know, you should verbally interpret the division by zero based on your problem. Please let me know if there are general rules about the ambiguity raised by this situation. So I will be able to update the codes.

Best regards,
Arslan

**Comment by Haghrah** [comment]
Hi!
Thanks a lot for writing to me!

This is the theoretical problem of the CoG defuzzification method. When you evaluate the Fuzzy rules, if a rule ends up with a Fuzzy set with zero membership value all over its domain, the denominator of the equation used to calculate the CoG would be zero. So if you try to calculate the CoG on a paper, you will also get division by zero. This problem originates from the fact that the trapezoid or triangular sets have zero membership value in some parts of their domain. Theoretically, this means that if you use Gaussian Fuzzy sets, you will not get trapped in such a situation. For example, using a triangular set "-1 is POSITIVE" yields an absolute zero, and then using a t-norm makes the resulting Fuzzy set an all zero Fuzzy set. But when you use Gaussian sets, it will be a small value like 0.0001, which prevents division by zero. This is about evaluating single rules, but when you use CoG for a whole system, there will not be an error. Because the resulting sets from each rule will be aggregated using an s-norm.

But wait, your problem is about CoA, not CoG!!! I know that, but in the CoA method, the sets achieved by each rule are defuzzified first! And it is done using the CoG in this toolkit. Consider that, while evaluating a fuzzy system, we are using the CoA and CoG to aggregate the achieved results from the fuzzy rules, not to defuzzify the fuzzy sets. These concepts are a bit different.

    def _CoG(self, B):
        C = {}
        D = {}
        for out in self.outputs:
            C[out] = T1FS(B[out][0].domain)
            for B_l in B[out]:
                C[out] = T1FS_OR(B_l.domain, C[out], B_l, max_s_norm)
            D[out] = C[out].defuzzify()
        return C, D

    def _CoA(self, B):
        D = {}
        for out in self.outputs:
            a = 0.
            b = 0.
            for B_l in B[out]:
                tmp = B_l.defuzzify()
                a += tmp * B_l(tmp)
                b += B_l(tmp)
            D[out] = a / b
        return D

Best regards,
Arslan

**Comment by Haghrah** [comment]
In short, I recommend you use Gaussian fuzzy sets, which are non-zero all over the domain and have a continuous derivative.

**Comment by guiaugustoga987** [comment]
Thank you for your response. I'll use Gaussian fuzzy sets and test it again.
